schema_version = "1.0.0"
id = "cases_addon"
name = "Instrument Cases AddOn"
version = "0.1.0"
tagline = "Make fittings for musical instrument cases"
maintainer = "DTRabbit"
type = "add-on"
tags = ["Mesh"]
blender_version_min = "4.5.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2026 DTRabbit"]
